#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const ENV_PATH = path.join(ROOT, ".env");
const TEMPLATE_PATH = path.join(ROOT, ".env.template");

const args = new Set(process.argv.slice(2));
const mode = args.has("--status")
  ? "status"
  : args.has("--westend")
  ? "westend"
  : args.has("--paseo")
    ? "paseo"
    : args.has("--local")
      ? "local"
      : "paseo";

function parseEnv(text) {
  /** @type {Record<string, string>} */
  const out = {};
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const idx = trimmed.indexOf("=");
    if (idx === -1) continue;
    const key = trimmed.slice(0, idx).trim();
    const value = trimmed.slice(idx + 1).trim();
    out[key] = value;
  }
  return out;
}

function renderEnv(vars) {
  const lines = [
    "# TeleBasket Environment Configuration",
    "# Generated by `node scripts/setup-env.js`",
    "",
  ];
  const orderedKeys = [
    "VITE_NETWORK",
    "VITE_RPC_URL",
    "VITE_CHAIN_ID",
    "VITE_GAS_PRICE_GWEI",
    "VITE_BASKET_MANAGER_ADDRESS",
    "VITE_PVM_ENGINE_ADDRESS",
    "VITE_USE_MOCK_PVM",
  ];
  const keys = [...new Set([...orderedKeys, ...Object.keys(vars).sort()])];
  for (const key of keys) {
    if (!(key in vars)) continue;
    lines.push(`${key}=${vars[key]}`);
  }
  lines.push("");
  return lines.join("\n");
}

function loadBase() {
  if (fs.existsSync(ENV_PATH)) return parseEnv(fs.readFileSync(ENV_PATH, "utf8"));
  if (fs.existsSync(TEMPLATE_PATH)) return parseEnv(fs.readFileSync(TEMPLATE_PATH, "utf8"));
  return {};
}

const base = loadBase();

const presets = {
  westend: {
    VITE_NETWORK: "westend",
    VITE_RPC_URL: "https://westend-asset-hub-eth-rpc.polkadot.io",
    VITE_CHAIN_ID: "420420421",
    VITE_GAS_PRICE_GWEI: "1100",
  },
  paseo: {
    VITE_NETWORK: "paseo",
    VITE_RPC_URL: "https://eth-rpc-testnet.polkadot.io",
    VITE_CHAIN_ID: "420420417",
    VITE_GAS_PRICE_GWEI: "1100",
  },
  local: {
    VITE_NETWORK: "paseo",
    VITE_RPC_URL: "http://127.0.0.1:8545",
    VITE_CHAIN_ID: "420420417",
    VITE_GAS_PRICE_GWEI: "1100",
  },
};

if (mode === "status") {
  const current = fs.existsSync(ENV_PATH) ? parseEnv(fs.readFileSync(ENV_PATH, "utf8")) : null;
  if (!current) {
    console.log("No .env found. Create one from .env.template or run one of:");
    console.log("  npm run env:westend");
    console.log("  npm run env:paseo");
    console.log("  npm run env:local");
    process.exit(0);
  }
  console.log("Current VITE_* env:");
  for (const key of Object.keys(current).filter((k) => k.startsWith("VITE_")).sort()) {
    console.log(`  ${key}=${current[key]}`);
  }
  process.exit(0);
}

const preset = presets[mode];
if (!preset) {
  console.error(`Unknown mode: ${mode}`);
  process.exit(1);
}

const next = { ...base, ...preset };
const rendered = renderEnv(next);
fs.mkdirSync(path.dirname(ENV_PATH), { recursive: true });
fs.writeFileSync(ENV_PATH, rendered, "utf8");
console.log(`Wrote ${ENV_PATH} for mode: ${mode}`);
